export const Theme = {
  colors: {
    RoyalBlue: "#3763EB",
    RoyalBlueLight: "#798fff",
    RoyalBlueDark: "#0039b7",
    Dolphin: "#6E657E",
    DolphinLight: "#9c93ad",
    DolphinDark: "#433b52",
    BlackPearl: "#081828",
    BlackPearlLight: "#303e50",
    BlackPearlDark: "#000000",
    DustyGray: "#999999",
    DustyGrayLight: "#cacaca",
    DustyGrayDark: "#6b6b6b",
    BlackSqueeze: "#f6f9fc",
    BlackSqueezeLight: "#ffffff",
    BlackSqueezeDark: "#c3c6c9",
  },
  typography: {
    component: {
      h1: "h1",
      h2: "h2",
      h3: "h3",
      h4: "h4",
      h5: "h5",
      h6: "h6",
      subline1: "p",
      subline2: "p",
      body1: "p",
      body2: "p",
      button: "span",
      caption: "span",
      overLine: "span",
    },
    fontSize: {
      h1: "125px",
      h2: "78px",
      h3: "63px",
      h4: "44px",
      h5: "31px",
      h6: "26px",
      subline1: "21px",
      subline2: "18px",
      body1: "21px",
      body2: "18px",
      button: "18px",
      caption: "16px",
      overLine: "13px",
    },
    lineHeight: {
      h1: "-1.5px",
      h2: "-0.5px",
      h3: "0",
      h4: "0.25px",
      h5: "0",
      h6: "0.15px",
      subline1: "0.15px",
      subline2: "0.1px",
      body1: "0.5px",
      body2: "0.15px",
      button: "1.25px",
      caption: "0.4px",
      overLine: "1.25px",
    },
    fontWeights: {
      thin: "100",
      extraLight: "200",
      light: "300",
      regular: "400",
      medium: "500",
      semiBold: "600",
      bold: "700",
      extraBold: "800",
      black: "900",
    },
  },
  button: {
    primary: {
      backgroundColor: "#ffffff",
      color: "#3763EB",
      border: "2px solid #3763EB",
    },
    secondary: {
      backgroundColor: "#3763EB",
      color: "#fff",
      border: "1px solid #3763EB",
    },
    ternary: {},
    outlinedbtn: {
      backgroundColor: "none",
      color: "#3763EB",
      border: "1px solid #3763EB",
    },
    textbtn: {
      border: "none",
      color: "#3763EB",
    },
    size: {
      small: {
        width: "135px",
        // height: "55px",
      },
      medium: {
        width: "150px",
        // height: "55px",
      },
      larg: {
        width: "165px",
        // height: "55px",
      },
      xlarge: {
        width: "180px",
        // height: "55px",
      },
    },
  },
};
